# Generated by Django 2.2.7 on 2020-08-25 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Image Title')),
                ('image', models.ImageField(blank=True, default='/media/products/product.png', upload_to='products', verbose_name='Product Image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Product', verbose_name='Product For Image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
