# Generated by Django 2.2.7 on 2020-08-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/media/products/product.png', upload_to='products', verbose_name='Product Image'),
        ),
    ]
