# Generated by Django 2.2.7 on 2020-08-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('true', 'True'), ('false', 'False')], max_length=10, verbose_name='Status')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Title')),
                ('keywords', models.CharField(blank=True, max_length=150, verbose_name='Keywords')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('company', models.CharField(blank=True, max_length=150, verbose_name='Company')),
                ('address', models.CharField(blank=True, max_length=150, verbose_name='Address')),
                ('phone', models.CharField(blank=True, max_length=150, verbose_name='Phone')),
                ('fax', models.CharField(blank=True, max_length=150, verbose_name='Fax')),
                ('email', models.CharField(blank=True, max_length=150, verbose_name='Email')),
                ('smtpserver', models.CharField(blank=True, max_length=150, verbose_name='Smtp Server')),
                ('smtpemail', models.CharField(blank=True, max_length=150, verbose_name='Smtp Email')),
                ('smtppassword', models.CharField(blank=True, max_length=150, verbose_name='Smtp Password')),
                ('smtpport', models.CharField(blank=True, max_length=150, verbose_name='Smtp Port')),
                ('icon', models.ImageField(blank=True, default='/media/products/product.png', upload_to='products', verbose_name='Icon')),
                ('facebook', models.CharField(blank=True, max_length=50, verbose_name='Facebook')),
                ('instagram', models.CharField(blank=True, max_length=50, verbose_name='Instagram')),
                ('twitter', models.CharField(blank=True, max_length=50, verbose_name='Twitter')),
                ('aboutus', models.TextField()),
                ('references', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
