# Generated by Django 2.2.7 on 2020-08-25 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='contactus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='aboutus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='references',
            field=models.TextField(blank=True, null=True),
        ),
    ]
