# Generated by Django 2.2.7 on 2020-08-24 10:40

import autoslug.fields
from django.conf import settings
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import main.users.manager.usermanager
import main.users.models.user


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254, unique=True, verbose_name='Email address')),
                ('pin', models.PositiveIntegerField(default=main.users.models.user.get_random_pin, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='PIN')),
                ('full_name', models.CharField(blank=True, default='', max_length=30, verbose_name='Full name')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='full_name', unique=True)),
                ('birthdate', models.DateField(null=True, verbose_name='Birth Date')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Is Staff')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('is_email', models.BooleanField(default=False, verbose_name='Is Email Verified')),
                ('role', models.CharField(choices=[('consumer', 'Consumer'), ('reseller', 'Reseller Client'), ('reseller manager', 'Reseller Manager'), ('admin', 'Administrator')], default='consumer', max_length=15, verbose_name='Role')),
                ('img', models.ImageField(blank=True, default='/media/users/user.png', upload_to='users', verbose_name='Avatar')),
                ('city', models.CharField(default='Istanbul', max_length=32, verbose_name='City')),
                ('country', models.CharField(default='TR', max_length=2, verbose_name='Country')),
                ('mob', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Your phone number should consist of 9-15 digits. Example: 1114442277', regex='(\\d{9,15})$')], verbose_name='Mobile')),
                ('push_notify', models.BooleanField(default=True, verbose_name='Push Notification')),
                ('newsletter', models.BooleanField(default=False, verbose_name='Email Newsletter')),
                ('lati', models.FloatField(default=0.0, verbose_name='Latitude')),
                ('lngt', models.FloatField(default=0.0, verbose_name='Longitude')),
                ('terms', models.BooleanField(default=False, verbose_name='Agree terms ')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='Username')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', main.users.manager.usermanager.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PasswordHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user_password', models.CharField(default='', max_length=350, unique=True, verbose_name='User Password')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Password History',
                'verbose_name_plural': 'Password Histories',
                'ordering': ('-created',),
            },
        ),
    ]
